// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx8WuDLaA2_UkZTQIBie5eZw8hK7ZJAMY',
    appId: '1:70806296331:web:17573771e3d02e96beb40e',
    messagingSenderId: '70806296331',
    projectId: 'spraying-app-web',
    authDomain: 'spraying-app-web.firebaseapp.com',
    storageBucket: 'spraying-app-web.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9m_dqh4tHMOPOdYTMbBn-b6HX_8jNe1k',
    appId: '1:70806296331:android:5a0ac49cf74d7123beb40e',
    messagingSenderId: '70806296331',
    projectId: 'spraying-app-web',
    storageBucket: 'spraying-app-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3elnRbAD55wqj-DIYJSZGeP1hK3yTJpE',
    appId: '1:70806296331:ios:ca88e2b4e4b358a8beb40e',
    messagingSenderId: '70806296331',
    projectId: 'spraying-app-web',
    storageBucket: 'spraying-app-web.firebasestorage.app',
    iosBundleId: 'com.example.sprayingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3elnRbAD55wqj-DIYJSZGeP1hK3yTJpE',
    appId: '1:70806296331:ios:ca88e2b4e4b358a8beb40e',
    messagingSenderId: '70806296331',
    projectId: 'spraying-app-web',
    storageBucket: 'spraying-app-web.firebasestorage.app',
    iosBundleId: 'com.example.sprayingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx8WuDLaA2_UkZTQIBie5eZw8hK7ZJAMY',
    appId: '1:70806296331:web:c3ada3013ca2372cbeb40e',
    messagingSenderId: '70806296331',
    projectId: 'spraying-app-web',
    authDomain: 'spraying-app-web.firebaseapp.com',
    storageBucket: 'spraying-app-web.firebasestorage.app',
  );
}
